### ISSUE TITLE
위치 지하철역 전체정보 조회

### ISSUE THREAD

**Issue by 5o-hyun** [swyp-mema/mema-server#67]
### 🐞 버그 내용

[GET] /meets/meetId/station/total

지하철역 전체정보 조회하는 해당 api에서 다음과같은 오류가 발생합니다.
{code: "I001", message: "서버 내부 오류가 발생했습니다."}

**Comment by codingbaraGo** [comment]
request 보내신 엔드포인트가 /meets/meetId/station/total 맞나요?
/station/total은 모든 지하철 역의 리스트를 조회해주고, /meets/meetId/vote/location/total은 'meetId'의 미팅내 모든 투표 현황 + 중간역을 조회해줍니다.
스웨거 상에는 이렇게 나오네요.
혹시 스웨거가 최근 수정되었나요?

**Comment by hikarigin99** [comment]
아.. 이거 말씀드리는거 깜빡했네요,,
최근 지하철역 전체 조회 API 경로 수정했습니다ㅠ.ㅠ

```
기존 :  /meets/{meetId}/station/total
수정 : /station/total
```

현창님이 말씀하신 것 처럼 `/meets/meetId/vote/location/total` 에서는 `약속원들의 출발 위치 + 중간 지점` 값!이 포함되어 있습니다
한번에 여러개를 수정하니 말씀드린다는 것을 깜빡했네요 죄송합니다😭

로그인 후 해당 API 호출하시면 200 응답뜨는거 확인했습니다🥲
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/10458576-f822-4d24-a010-7a39e9c1fa97" />

**Comment by 5o-hyun** [comment]
> request 보내신 엔드포인트가 /meets/meetId/station/total 맞나요? /station/total은 모든 지하철 역의 리스트를 조회해주고, /meets/meetId/vote/location/total은 'meetId'의 미팅내 모든 투표 현황 + 중간역을 조회해줍니다. 스웨거 상에는 이렇게 나오네요. 혹시 스웨거가 최근 수정되었나요?

스웨거 수정했냐고 물어보셨는데  제가 스웨거를 수정하는부분이 아니기떄문에 저한테물어보셔도모릅니다......... 해당부분 은비님이 대답해주셨어요 확인해주시면될것같습니다

**Comment by codingbaraGo** [comment]
전체 역 조회는 은비님이 담당하시고 나머지 중간역 알고리즘은 지금 제가 수정중이라 엔드포인트가 수정되었는지 아닌지 몰라서 질문드렸습니다.

혹시 스웨거가 최근 수정되었나요? ==> 스웨거상 엔드포인트가 수정되었는지 물어본거였습니다. 이슈 올리신거 보고 스웨거를 봤더니 엔드포인트가 달랐기에 엔드포인트가 바뀌어 문제가 생긴건지 서버 내부 문제인지 체크하려구요.
생각해보니 그냥 은비님이 답하는게 맞았는듯 하네요.

앞으론 이런 수정사항 있으면 꼭 전달하도록 하겠습니다
죄송해요

**Comment by 5o-hyun** [comment]
수정완료되어 이슈를 종료합니다
